/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBanner {
    }
    interface AppFooter {
        "baseUrl": string;
        "instagram": string;
        "twitter": string;
        "youtube": string;
    }
    interface AppHeader {
        "imageSrc": string;
    }
    interface AppHome {
    }
    interface AppNavLink {
        "current": boolean;
        "href": string;
    }
    interface AppNavbar {
    }
    interface AppRoot {
    }
    interface AppShopping {
    }
}
declare global {
    interface HTMLAppBannerElement extends Components.AppBanner, HTMLStencilElement {
    }
    var HTMLAppBannerElement: {
        prototype: HTMLAppBannerElement;
        new (): HTMLAppBannerElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppNavLinkElement extends Components.AppNavLink, HTMLStencilElement {
    }
    var HTMLAppNavLinkElement: {
        prototype: HTMLAppNavLinkElement;
        new (): HTMLAppNavLinkElement;
    };
    interface HTMLAppNavbarElement extends Components.AppNavbar, HTMLStencilElement {
    }
    var HTMLAppNavbarElement: {
        prototype: HTMLAppNavbarElement;
        new (): HTMLAppNavbarElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppShoppingElement extends Components.AppShopping, HTMLStencilElement {
    }
    var HTMLAppShoppingElement: {
        prototype: HTMLAppShoppingElement;
        new (): HTMLAppShoppingElement;
    };
    interface HTMLElementTagNameMap {
        "app-banner": HTMLAppBannerElement;
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-nav-link": HTMLAppNavLinkElement;
        "app-navbar": HTMLAppNavbarElement;
        "app-root": HTMLAppRootElement;
        "app-shopping": HTMLAppShoppingElement;
    }
}
declare namespace LocalJSX {
    interface AppBanner {
    }
    interface AppFooter {
        "baseUrl"?: string;
        "instagram"?: string;
        "twitter"?: string;
        "youtube"?: string;
    }
    interface AppHeader {
        "imageSrc"?: string;
    }
    interface AppHome {
    }
    interface AppNavLink {
        "current"?: boolean;
        "href"?: string;
    }
    interface AppNavbar {
    }
    interface AppRoot {
    }
    interface AppShopping {
    }
    interface IntrinsicElements {
        "app-banner": AppBanner;
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-nav-link": AppNavLink;
        "app-navbar": AppNavbar;
        "app-root": AppRoot;
        "app-shopping": AppShopping;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-banner": LocalJSX.AppBanner & JSXBase.HTMLAttributes<HTMLAppBannerElement>;
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-nav-link": LocalJSX.AppNavLink & JSXBase.HTMLAttributes<HTMLAppNavLinkElement>;
            "app-navbar": LocalJSX.AppNavbar & JSXBase.HTMLAttributes<HTMLAppNavbarElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-shopping": LocalJSX.AppShopping & JSXBase.HTMLAttributes<HTMLAppShoppingElement>;
        }
    }
}
